server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blocks?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root